### PR TITLE
add Pinterval

### PR DESCRIPTION
**Pull request by LucaDanieli**
add pattern

### CODE REVIEW

**Comment by muellmusik** [comment]
Hey Luca, are you happy with the name suggestion? I'm going to quickly do PnumJets and PnumConstituents now.

**Comment by LucaDanieli** [comment]
Yep, I couldn't do it yesterday as I had old stuff to work on, so I have made some space in my schedule to work on it tonight and tomorrow morning.

**Comment by LucaDanieli** [comment]
I think I will do at least another pattern that make a comparison between different jets:

for example: 
jet(1) ("phi"[0]) - jet(2) ("phi"[0]), 
jet(1) ("phi"[1]) - jet(2) ("phi"[1]),
jet(1) ("phi"[2]) - jet(2) ("phi"[2]),
...

I think this would be useful

**Comment by muellmusik** [comment]
> I think I will do at least another pattern that make a comparison between different jets:
> 
> for example: 
> jet1 - jet2, 
> jet1 - jet2,
> jet1 - jet2,
> ...

So you mean the values it holds would be the difference between two jets? You can do that now with Pjet(a) - Pjet(b) of course.

BTW, this PR now has some conflicts. Sorry...

**Comment by LucaDanieli** [comment]
No sorry, my mistake:

jet(1) (constituent(0)["phi"]) - jet(2) (constituent(0)["phi"]), 
jet(1) (constituent(1)["phi"]) - jet(2) (constituent(1)["phi"]),
jet(1) (constituent(2)["phi"]) - jet(2) (constituent(2)["phi"]),
..

So that they are always in syncs.

something like:
Pconstituent(0, Pseq((0..3), \inf)) - Pconstituent(1, Pseq((0..3), \inf))
into => Pdiff(0, 1, \key)

what is the conflict? Do I have to solve it?

**Comment by muellmusik** [comment]
> On 14 Mar 2016, at 10:00, LucaDanieli notifications@github.com wrote:
> 
> No sorry, my mistake:
> 
> jet(1) (constituent(0)["phi"]) - jet(2) (constituent(0)["phi"]), 
> jet(1) (constituent(1)["phi"]) - jet(2) (constituent(1)["phi"]),
> jet(1) (constituent(2)["phi"]) - jet(2) (constituent(2)["phi"]),
> ..
> 
> So that they are always in syncs.
> 
> something like:
> Pconstituent(0, Pseq((0..3), \inf)) - Pconstituent(1, Pseq((0..3), \inf))
> into => Pdiff(0, 1, \key)
> 
> Okay.
> what is the conflict? Do I have to solve it?
> 
> No. I’d just do a new PR against current master. Easier if you separate the commits for classes and examples.

S.

**Comment by muellmusik** [comment]
I've pushed those other patterns now.

**Comment by muellmusik** [comment]
Superseded by 2

**Pull request closed without merging**
