### PR TITLE
add PjetMean

### PR DESCRIPTION
**Pull request by LucaDanieli**

### CODE REVIEW

**Comment by muellmusik** [comment]
Oops. As is this will just revert more recent changes in master. @LucaDanieli, I'm going to just make a new commit with your class.

**Comment by muellmusik** [comment]
Actually a query first:

```
if (which.asString == "jet", {
            jetStream = jetnum.asStream;
            keyStream = jetStream.asStream;
        }, {
            jetStream = jetnum.asStream;
            keyStream = which.asStream;
        });
```

Is that meant to compare either jets or constituents? Would it make sense to have separate classes for that?

**Comment by LucaDanieli** [comment]
Yep, I was wondering the same. Would you like to split that in two different patterns?

**Comment by muellmusik** [comment]
Yes I think so.

**Pull request closed without merging**
